# Generated by Django 3.0.8 on 2021-01-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
