# Generated by Django 3.0.8 on 2021-02-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210211_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
